Repository nasa/GSAP, pull requests merged in 2018-09, with the labels that each got.

#72 Added additional Operators to Matrix Class
  Test/gsapTests/MatrixTests.cpp
  Test/gsapTests/MatrixTests.h
  inc/Matrix.h
  src/Matrix.cpp
Labels: enhancement

#73 Trajectory Services and Savepoint Providers
  CMakeLists.txt
  Test/gsapTests/CMakeLists.txt
  Test/gsapTests/MockClasses.h
  Test/gsapTests/PredictorTests.cpp
  Test/gsapTests/Predictors/EventDrivenPredictorTests.cpp
  Test/gsapTests/TrajectoryServiceTests.cpp
  Test/gsapTests/TrajectoryServiceTests.h
  Test/gsapTests/main.cpp
  inc/CompositeSavePointProvider.h
  inc/EventDrivenTrajectoryService.h
  inc/ISavePointProvider.h
  inc/ITrajectoryCorrelator.h
  inc/Loading/LoadEstimator.h
  inc/Messages/MessageId.h
  inc/Messages/WaypointMessage.h
  inc/Observers/ParticleFilter.h
  inc/Observers/UnscentedKalmanFilter.h
  inc/Point3D.h
  inc/Predictors/EventDrivenPredictor.h
  inc/Predictors/MonteCarloPredictor.h
  inc/Predictors/Predictor.h
  inc/Predictors/PredictorFactory.h
  inc/Trajectory/Waypoint.h
  inc/TrajectoryService.h
  src/EventDrivenTrajectoryService.cpp
  src/Messages/MessageId.cpp
  src/Messages/WaypointMessage.cpp
  src/ModelBasedPrognoser.cpp
  src/Predictors/MonteCarloPredictor.cpp
  src/TrajectoryService.cpp
  templates/EmptyPredictor.cpp
  templates/EmptyPredictor.h
Labels: A: Load Estimation, A: Predictors, A: Trajectory, C: Enhancement, PR: Delete Branch, PR: Merge, S: Waiting on Checks

#76 Add missing default virtual destructors
  inc/ISavePointProvider.h
  inc/ITrajectoryCorrelator.h
  inc/Loading/LoadEstimator.h
  inc/Messages/IMessageProcessor.h
  inc/Messages/IMessagePublisher.h
Labels: A: Load Estimation, A: Messaging, A: Trajectory, C: Bug, PR: Keep Branch, PR: Merge, S: Waiting on Checks

#79 Fix incorrect dereference of end iterator in MC predictor
  src/Predictors/MonteCarloPredictor.cpp
Labels: A: Predictors, C: Bug, PR: Keep Branch, PR: Merge, S: Review

#81 Jason watkins
  .appveyor.yml
Labels: C: Test, PR: Keep Branch, PR: Merge, S: Review

#82 Fix missing propogation of message timestamps
  .appveyor.yml
  Test/gsapTests/Predictors/EventDrivenPredictorTests.cpp
  inc/Messages/MessageWatcher.h
  inc/Observers/EventDrivenObserver.h
  src/Observers/EventDrivenObserver.cpp
  src/Predictors/EventDrivenPredictor.cpp
Labels: A: Messaging, C: Bug, PR: Keep Branch, PR: Merge, S: Review

#84 Reorganize code to minimize header bloat
  CMakeLists.txt
  Test/RunTests.ps1
  Test/gsapTests/Loading/ConstLoadEstimatorTests.cpp
  Test/gsapTests/Loading/GaussianLoadEstimatorTests.cpp
  Test/gsapTests/Loading/MovingAverageLoadEstimatorTests.cpp
  Test/gsapTests/Messages/MessageWatcherTests.cpp
  Test/gsapTests/MockClasses.h
  Test/gsapTests/Observers/EventDrivenObserverTests.cpp
  Test/gsapTests/Predictors/EventDrivenPredictorTests.cpp
  Test/gsapTests/TrajectoryServiceTests.cpp
  inc/Loading/ConstLoadEstimator.h
  inc/Loading/GaussianLoadEstimator.h
  inc/Loading/LoadEstimator.h
  inc/Loading/MovingAverageLoadEstimator.h
  inc/Messages/EmptyMessage.h
  inc/Messages/Message.h
  inc/Messages/MessageClock.h
  inc/Messages/MessageWatcher.h
  inc/Messages/ProgEventMessage.h
  inc/Messages/ScalarMessage.h
  inc/Messages/UDataMessage.h
  inc/Messages/VectorMessage.h
  inc/Messages/WaypointMessage.h
  inc/Observers/EventDrivenObserver.h
  src/Loading/ConstLoadEstimator.cpp
  src/Loading/GaussianLoadEstimator.cpp
  src/Loading/MovingAverageLoadEstimator.cpp
  src/Messages/EmptyMessage.cpp
  src/Messages/Message.cpp
  src/Messages/WaypointMessage.cpp
  src/Observers/EventDrivenObserver.cpp
  src/Trajectory/EventDrivenTrajectoryService.cpp
Labels: A: Load Estimation, A: Messaging, C: Cleanup, PR: Keep Branch, PR: Merge, S: Review

#85 Remove message default-timestamp constructor
  Test/gsapTests/Messages/MessageBusTests.cpp
  Test/gsapTests/Messages/MessageWatcherTests.cpp
  Test/gsapTests/Observers/EventDrivenObserverTests.cpp
  Test/gsapTests/TrajectoryServiceTests.cpp
  inc/Messages/Message.h
  inc/Messages/ScalarMessage.h
  inc/Messages/VectorMessage.h
  src/Messages/MessageWatcher.cpp
Labels: A: Messaging, C: Enhancement, PR: Keep Branch, PR: Merge, S: Review

#90 Messaging
  Test/gsapTests/CMakeLists.txt
  Test/gsapTests/Messages/MessageBusTests.cpp
  Test/gsapTests/Messages/MessageBusTests.h
  Test/gsapTests/Messages/MessageWatcherTests.cpp
  Test/gsapTests/Observers/EventDrivenObserverTests.cpp
  Test/gsapTests/Predictors/EventDrivenPredictorTests.cpp
  Test/gsapTests/TrajectoryServiceTests.cpp
  Test/gsapTests/main.cpp
  inc/Messages/MessageBus.h
  inc/Messages/MessageId.h
  src/Messages/MessageBus.cpp
Labels: A: Messaging, C: Bug, C: Enhancement, PR: Delete Branch, PR: Merge

#91 Fixed Savepts and SysTrajectories
  Test/gsapTests/Predictors/EventDrivenPredictorTests.cpp
  Test/gsapTests/Predictors/EventDrivenPredictorTests.h
  Test/gsapTests/main.cpp
  src/Predictors/MonteCarloPredictor.cpp
Labels: A: Predictors, A: Trajectory, C: Bug, C: Test, E: Easy, PR: Delete Branch, PR: Merge, S: Waiting on Review

#93 Updates to expose data required by SWS metrics
  inc/Matrix.h
  inc/Trajectory/TrajectoryService.h
Labels: C: Enhancement, PR: Delete Branch, PR: Merge, S: Waiting on Review
