Repository nasa/GSAP, pull requests merged in 2019-02, with the labels that each got.

#112 Remove unused Thread class
  CMakeLists.txt
  inc/Thread.h
  src/Thread.cpp
  tests/CMakeLists.txt
  tests/src/ThreadTests.cpp
  tests/src/main.cpp
Labels: C: Cleanup, PR: Keep Branch, PR: Merge, S: Waiting on Review

#115 Make MessageClock::rep signed
  inc/Messages/MessageClock.h
Labels: A: Messaging, C: Bug, PR: Keep Branch, PR: Merge, S: Waiting on Checks

#111 Added Integration Tests & Fix for PF->MC
  src/Predictors/MonteCarloPredictor.cpp
  tests/CMakeLists.txt
  tests/data/data_const_load.csv
  tests/src/AsyncIntegrationTests.cpp
  tests/src/SyncIntegrationTests.cpp
  tests/src/main.cpp
Labels: C: Bug, C: Test, PR: Delete Branch

#114 Fix all existing compiler warnings on Windows and Linux GCC/Clang
  inc/Prognoser.h
  src/AsyncPrognoserBuilder.cpp
  src/Matrix.cpp
  src/ModelBasedAsyncPrognoserBuilder.cpp
  src/ModelBasedPrognoser.cpp
  src/Predictors/MonteCarloPredictor.cpp
  templates/EmptyCommunicator.cpp
  templates/EmptyCommunicator.h
  templates/EmptyModel.cpp
  templates/EmptyObserver.cpp
  templates/EmptyPredictor.cpp
  templates/EmptyPrognoser.cpp
  templates/EmptyPrognosticsModel.cpp
  tests/inc/MockClasses.h
  tests/src/ConfigMapTests.cpp
  tests/src/DPointTests.cpp
  tests/src/DynamicArrayTests.cpp
  tests/src/GaussianVariableTests.cpp
  tests/src/Loading/ConstLoadEstimatorTests.cpp
  tests/src/Loading/GaussianLoadEstimatorTests.cpp
  tests/src/Loading/MovingAverageLoadEstimatorTests.cpp
  tests/src/MatrixTests.cpp
  tests/src/StatisticalToolsTests.cpp
  tests/src/TestPrognoser.cpp
  tests/src/TrajectoryServiceTests.cpp
  tests/src/UDataTests.cpp
Labels: C: Cleanup, PR: Delete Branch, PR: Merge, S: Waiting on Checks
